# Compile every file under skills/<name>/ into the binary.
#   cmake -DSRC=<skills dir> -DOUT=<file.cpp> -P embed_skills.cmake
file(GLOB_RECURSE FILES RELATIVE "${SRC}" "${SRC}/*")
list(FILTER FILES EXCLUDE REGEX "(^|/)(__pycache__|\\.)")
list(SORT FILES)
set(BODY "")
set(ENTRIES "")
set(I 0)
foreach(REL ${FILES})
  string(FIND "${REL}" "/" SLASH)
  if(SLASH EQUAL -1)
    continue()
  endif()
  string(SUBSTRING "${REL}" 0 ${SLASH} NAME)
  math(EXPR START "${SLASH} + 1")
  string(SUBSTRING "${REL}" ${START} -1 PATH)
  file(READ "${SRC}/${REL}" HEX HEX)
  string(LENGTH "${HEX}" LEN)
  math(EXPR SIZE "${LEN} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${HEX}")
  string(APPEND BODY "static const unsigned char f${I}[] = {${BYTES}0};\n")
  string(APPEND ENTRIES "      {\"${NAME}\", \"${PATH}\", std::string_view(reinterpret_cast<const char*>(f${I}), ${SIZE})},\n")
  math(EXPR I "${I} + 1")
endforeach()
file(WRITE "${OUT}.tmp" "// Generated from skills/; do not edit.\n#include \"shaman/skill/skill.hpp\"\nnamespace shaman::embedded {\n${BODY}const std::vector<SkillFile>& skill_files() {\n  static const std::vector<SkillFile> files = {\n${ENTRIES}  };\n  return files;\n}\n}\n")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
